[package]
name = "netport"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.3.2"
once_cell = "1.10.0"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"